services:
  php:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: estoque
    ports:
      - "3307:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      